import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'registry/default/index.ts',
    'lib/utils': 'registry/default/lib/utils.ts',
    'ui/accordion': 'registry/default/ui/accordion.tsx',
    'ui/back-link': 'registry/default/ui/back-link.tsx',
    'ui/breadcrumbs': 'registry/default/ui/breadcrumbs.tsx',
    'ui/button': 'registry/default/ui/button.tsx',
    'ui/character-count': 'registry/default/ui/character-count.tsx',
    'ui/checkboxes': 'registry/default/ui/checkboxes.tsx',
    'ui/details': 'registry/default/ui/details.tsx',
    'ui/error-message': 'registry/default/ui/error-message.tsx',
    'ui/error-summary': 'registry/default/ui/error-summary.tsx',
    'ui/fieldset': 'registry/default/ui/fieldset.tsx',
    'ui/footer': 'registry/default/ui/footer.tsx',
    'ui/header': 'registry/default/ui/header.tsx',
    'ui/hint': 'registry/default/ui/hint.tsx',
    'ui/inset-text': 'registry/default/ui/inset-text.tsx',
    'ui/label': 'registry/default/ui/label.tsx',
    'ui/link': 'registry/default/ui/link.tsx',
    'ui/notification-banner': 'registry/default/ui/notification-banner.tsx',
    'ui/pagination': 'registry/default/ui/pagination.tsx',
    'ui/panel': 'registry/default/ui/panel.tsx',
    'ui/phase-banner': 'registry/default/ui/phase-banner.tsx',
    'ui/radios': 'registry/default/ui/radios.tsx',
    'ui/select': 'registry/default/ui/select.tsx',
    'ui/skip-link': 'registry/default/ui/skip-link.tsx',
    'ui/summary-list': 'registry/default/ui/summary-list.tsx',
    'ui/tag': 'registry/default/ui/tag.tsx',
    'ui/tabs': 'registry/default/ui/tabs.tsx',
    'ui/table': 'registry/default/ui/table.tsx',
    'ui/task-list': 'registry/default/ui/task-list.tsx',
    'ui/text-input': 'registry/default/ui/text-input.tsx',
    'ui/textarea': 'registry/default/ui/textarea.tsx',
    'ui/warning-text': 'registry/default/ui/warning-text.tsx',
  },
  format: ['esm'],
  tsconfig: 'tsconfig.lib.json',
  dts: true,
  splitting: true,
  treeshake: true,
  clean: true,
  outDir: 'dist',
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    '@base-ui/react',
    '@base-ui/react/*',
  ],
  esbuildOptions(options) {
    options.alias = {
      '@': './registry/default',
    };
  },
});
